import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const EUROPE=new Set(["Albania","Andorra","Armenia","Austria","Azerbaijan","Belarus","Belgium","Bosnia","Bosnia and Herzegovina","Bulgaria","Croatia","Cyprus","Czech Republic","Czechia","Denmark","England","Estonia","Faroe Islands","Finland","France","Georgia","Germany","Gibraltar","Greece","Hungary","Iceland","Ireland","Italy","Kazakhstan","Kosovo","Latvia","Liechtenstein","Lithuania","Luxembourg","Malta","Moldova","Monaco","Montenegro","Netherlands","North Macedonia","Northern Ireland","Norway","Poland","Portugal","Romania","Russia","San Marino","Scotland","Serbia","Slovakia","Slovenia","Spain","Sweden","Switzerland","Turkey","Ukraine","Wales","United Kingdom","Republic of Ireland"]);
const VOID=new Set(["cancelled","canceled","postponed","abandoned","suspended"]);
const out=(status:number,data:any)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-headers":"authorization,apikey,content-type"}});
const norm=(s:any)=>String(s||"").toLowerCase().normalize("NFKD").replace(/[\\u0300-\\u036f]/g,"").replace(/[^a-z0-9 ]/g," ").replace(/\\s+/g," ").trim();
const european=(m:any)=>{const c=String(m.raw?.country||m.country||"");const league=String(m.league||"");const lc=league.split(" · ")[0];const text=league+" "+String(m.type||m.raw?.type||"");const uefa=/uefa\s+(champions league|europa league|conference league|europa conference league|nations league|super cup)/i.test(league);return(EUROPE.has(c)||EUROPE.has(lc)||uefa)&&!/friendly|test match/i.test(text)};
const softmax=(a:number[])=>{const mx=Math.max(...a),e=a.map(x=>Math.exp(x-mx)),s=e.reduce((a,b)=>a+b,0);return e.map(x=>x/s)};
async function getSettings(){try{const {data}=await sb.from("football_ai_settings").select("*").eq("id",true).maybeSingle();if(data)return data}catch{}return{football_api_enabled:true,odds_api_enabled:true,groq_enabled:true,openai_enabled:true,news_enabled:true}}
async function getMatches(){const {data,error}=await sb.from("football_matches").select("*").gte("kickoff_at",new Date().toISOString()).order("kickoff_at").limit(1000);if(error)throw error;return (data||[]).filter(european)}
async function getStats(){const {data,error}=await sb.from("football_team_stats").select("*").limit(5000);if(error)throw error;return data||[]}
function preScore(m:any,stats:any[],w:any){const h=stats.find(x=>norm(x.team_name)===norm(m.home_team)),a=stats.find(x=>norm(x.team_name)===norm(m.away_team));const hf=Number(h?.wins||0)-Number(h?.losses||0),af=Number(a?.wins||0)-Number(a?.losses||0),hg=Number(h?.goals_for||0)-Number(h?.goals_against||0),ag=Number(a?.goals_for||0)-Number(a?.goals_against||0),hx=Number(h?.xg_for||0)-Number(h?.xg_against||0),ax=Number(a?.xg_for||0)-Number(a?.xg_against||0);const edge=.35*(hf-af)+.08*(hg-ag)+.12*(hx-ax)+.35;const ww=w&&typeof w.home==="number"&&typeof w.draw==="number"&&typeof w.away==="number"?w:{home:1,draw:.1,away:-1};const p=softmax([edge*ww.home,Math.abs(edge)*ww.draw,(-edge)*ww.away]);const selected=p[0]>=p[2]&&p[0]>=p[1]?"1":p[2]>=p[1]?"2":"X";return {p,selected,confidence:Math.max(...p),score:Math.max(...p)*100,features:{hf,af,hg,ag,hx,ax}}}
async function newsFor(m:any){const q=encodeURIComponent(String(m.home_team)+" "+String(m.away_team)+" football");try{const r=await fetch("https://api.gdeltproject.org/api/v2/doc/doc?query="+q+"&mode=artlist&maxrecords=6&format=json&sort=datedesc");if(!r.ok)return[];const j=await r.json();return (j.articles||[]).map((a:any)=>({title:a.title,source:a.domain||a.source,url:a.url,published_at:a.seendate?new Date(a.seendate).toISOString():null,relevance:.7,summary:a.title}));}catch{return[]}}
async function deep(m:any,s:any,ns:any[],odds:any[]){const fallback={prediction:m.model.selected,confidence:Math.round(m.model.confidence*100),probabilities:{home:m.model.p[0],draw:m.model.p[1],away:m.model.p[2]},value_percent:null,risk:"Ukjent",reasoning:["Statistisk pre-score brukt fordi ingen aktiv AI-provider er tilgjengelig."],provider:"statistical",model:"pre-score"};let url="",key="",model="";if(s.groq_enabled&&Deno.env.get("GROQ_API_KEY")){url="https://api.groq.com/openai/v1/chat/completions";key=Deno.env.get("GROQ_API_KEY")!;model=Deno.env.get("GROQ_MODEL")||"llama-3.3-70b-versatile"}else if(s.openai_enabled&&Deno.env.get("OPENAI_API_KEY")){url="https://api.openai.com/v1/chat/completions";key=Deno.env.get("OPENAI_API_KEY")!;model=Deno.env.get("OPENAI_MODEL")||"gpt-4o-mini"}else return fallback;const prompt="Analyze this European football match and return JSON only with prediction, confidence, probabilities, value_percent, risk and reasoning. Match: "+m.home_team+" vs "+m.away_team+". Pre-score: "+JSON.stringify(m.model)+". Odds: "+JSON.stringify(odds.slice(0,8))+". News: "+JSON.stringify(ns.slice(0,6));const r=await fetch(url,{method:"POST",headers:{"authorization":"Bearer "+key,"content-type":"application/json"},body:JSON.stringify({model,messages:[{role:"system",content:"You are TradeMindMZ football AI. Do not invent facts. Return valid JSON only."},{role:"user",content:prompt}],temperature:.1,response_format:{type:"json_object"}})});if(!r.ok)return fallback;const j=await r.json();const x=JSON.parse(j.choices?.[0]?.message?.content||"{}");return {...fallback,...x,provider:url.includes("groq")?"groq":"openai",model}}
let lastFootballSync=0,lastOddsSync=0;
const API_TIMEOUT=9000;
const env=(name:string,fallback="")=>Deno.env.get(name)||fallback;
async function jsonFetch(url:string,init:RequestInit={},timeout=API_TIMEOUT){const ac=new AbortController();const t=setTimeout(()=>ac.abort(),timeout);try{const r=await fetch(url,{...init,signal:ac.signal});const text=await r.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(data?.message||data?.errors?.[0]?.message||("HTTP "+r.status));return{data,headers:r.headers}}finally{clearTimeout(t)}}
const apiDate=(d:Date)=>d.toISOString().slice(0,10);
async function syncFootball(){
  const sportmonks=env("SPORTMONKS_API_TOKEN")||env("SPORT_API_KEY");
  const provider=env("FOOTBALL_PROVIDER","auto").toLowerCase();
  if((provider==="sportmonks"||provider==="auto")&&sportmonks){
    const base=env("SPORTMONKS_API_BASE_URL","https://api.sportmonks.com/v3/football");
    const from=apiDate(new Date(Date.now()-30*86400000)),to=apiDate(new Date(Date.now()+7*86400000));
    let page=1,fixtures:any[]=[];
    try{
      for(let i=0;i<20;i++){
        const j=(await jsonFetch(base+"/fixtures/between/"+from+"/"+to+"?api_token="+encodeURIComponent(sportmonks)+"&include=participants;scores;league;state&per_page=50&page="+page,{headers:{accept:"application/json"}},12000)).data;
        const rows=Array.isArray(j?.data)?j.data:[];
        fixtures.push(...rows);
        if(!j?.pagination?.has_more||!rows.length)break;
        page++;
      }
    }catch(e){
      return{configured:true,provider:"sportmonks",synced:0,error:e instanceof Error?e.message:String(e)};
    }
    let synced=0,failed=0;
    for(const f of fixtures){
      const participants=Array.isArray(f.participants)?f.participants:[];
      const home=participants.find((p:any)=>p.meta?.location==="home"||p.location==="home")||participants[0];
      const away=participants.find((p:any)=>p.meta?.location==="away"||p.location==="away")||participants[1];
      const scores=Array.isArray(f.scores)?f.scores:[];
      const current=scores.find((s:any)=>String(s.description||s.type?.code||"").toUpperCase()==="CURRENT")||scores[0];
      const homeScore=scores.find((s:any)=>s.participant_id===home?.id&&s.description==="CURRENT")?.score?.goals??current?.score?.goals??null;
      const awayScore=scores.find((s:any)=>s.participant_id===away?.id&&s.description==="CURRENT")?.score?.goals??null;
      const leagueName=String(f.league?.name||"");
      const row={home_team:home?.name,away_team:away?.name,league:"Europe · "+leagueName,kickoff_at:f.starting_at,status:String(f.state?.short_name||f.state?.developer_name||f.state?.name||"NS"),home_score:homeScore,away_score:awayScore};
      if(!row.home_team||!row.away_team||!row.kickoff_at)continue;
      if(!european(row))continue;
      const {data:existingRows}=await sb.from("football_matches").select("id,home_team,away_team,kickoff_at").eq("home_team",row.home_team).eq("away_team",row.away_team).gte("kickoff_at",new Date(new Date(row.kickoff_at).getTime()-120000).toISOString()).lte("kickoff_at",new Date(new Date(row.kickoff_at).getTime()+120000).toISOString()).limit(1);
      const existing=existingRows?.[0]; let q:any;
      if(existing?.id)q=await sb.from("football_matches").update(row).eq("id",existing.id);else q=await sb.from("football_matches").insert(row);
      if(q.error)failed++;else synced++;
    }
    const {data:recent}=await sb.from("football_matches").select("home_team,away_team,status,home_score,away_score").gte("kickoff_at",new Date(Date.now()-30*86400000).toISOString()).not("home_score","is",null).limit(3000);
    const agg=new Map<string,any>();
    for(const m of recent||[]){const hs=Number(m.home_score),as=Number(m.away_score);for(const side of ["home","away"]){const team=side==="home"?m.home_team:m.away_team;if(!team)continue;const gf=side==="home"?hs:as,ga=side==="home"?as:hs;const x=agg.get(norm(team))||{team_name:team,wins:0,losses:0,draws:0,goals_for:0,goals_against:0,xg_for:0,xg_against:0};x.goals_for+=gf;x.goals_against+=ga;if(gf>ga)x.wins++;else if(gf<ga)x.losses++;else x.draws++;agg.set(norm(team),x)}}
    let statsSynced=0;for(const x of agg.values()){const {data:old}=await sb.from("football_team_stats").select("id").eq("team_name",x.team_name).limit(1).maybeSingle();const q=old?.id?await sb.from("football_team_stats").update(x).eq("id",old.id):await sb.from("football_team_stats").insert(x);if(!q.error)statsSynced++}
    return{configured:true,provider:"sportmonks",synced,stats_synced:statsSynced,failed,total:fixtures.length,from,to,pages:page};
  }
  const key=env("FOOTBALL_API_KEY"),base=env("FOOTBALL_API_BASE_URL","https://v3.football.api-sports.io");
  if(!key)return{configured:false,synced:0,error:"No football provider token configured"};
  const from=new Date(Date.now()-30*86400000),to=new Date(Date.now()+7*86400000);let payload:any;
  try{payload=(await jsonFetch(base+"/fixtures?from="+apiDate(from)+"&to="+apiDate(to)+"&timezone=UTC",{headers:{"x-apisports-key":key,"accept":"application/json"}})).data}catch(e){return{configured:true,provider:"api-football",synced:0,error:e instanceof Error?e.message:String(e)}}
  if(payload?.errors&&Object.keys(payload.errors).length)return{configured:true,provider:"api-football",synced:0,error:JSON.stringify(payload.errors)};
  const fixtures=Array.isArray(payload?.response)?payload.response:[];let synced=0,failed=0;
  for(const f of fixtures){const row={home_team:f.teams?.home?.name,away_team:f.teams?.away?.name,league:String(f.league?.country||"")+" · "+String(f.league?.name||""),kickoff_at:f.fixture?.date,status:f.fixture?.status?.short,home_score:f.goals?.home,away_score:f.goals?.away};if(!row.home_team||!row.away_team||!european(row))continue;const {data:existingRows}=await sb.from("football_matches").select("id,home_team,away_team,kickoff_at").eq("home_team",row.home_team).eq("away_team",row.away_team).gte("kickoff_at",new Date(new Date(row.kickoff_at).getTime()-120000).toISOString()).lte("kickoff_at",new Date(new Date(row.kickoff_at).getTime()+120000).toISOString()).limit(1);const existing=existingRows?.[0];let q:any;if(existing?.id)q=await sb.from("football_matches").update(row).eq("id",existing.id);else q=await sb.from("football_matches").insert(row);if(q.error)failed++;else synced++}
  const {data:recent}=await sb.from("football_matches").select("home_team,away_team,status,home_score,away_score").gte("kickoff_at",new Date(Date.now()-30*86400000).toISOString()).not("home_score","is",null).limit(3000);const agg=new Map<string,any>();for(const m of recent||[]){const hs=Number(m.home_score),as=Number(m.away_score);for(const side of ["home","away"]){const team=side==="home"?m.home_team:m.away_team;if(!team)continue;const gf=side==="home"?hs:as,ga=side==="home"?as:hs;const x=agg.get(norm(team))||{team_name:team,wins:0,losses:0,draws:0,goals_for:0,goals_against:0,xg_for:0,xg_against:0};x.goals_for+=gf;x.goals_against+=ga;if(gf>ga)x.wins++;else if(gf<ga)x.losses++;else x.draws++;agg.set(norm(team),x)}}let statsSynced=0;for(const x of agg.values()){const {data:old}=await sb.from("football_team_stats").select("id").eq("team_name",x.team_name).limit(1).maybeSingle();const q=old?.id?await sb.from("football_team_stats").update(x).eq("id",old.id):await sb.from("football_team_stats").insert(x);if(!q.error)statsSynced++}return{configured:true,provider:"api-football",synced,stats_synced:statsSynced,failed,total:fixtures.length,from:apiDate(from),to:apiDate(to)};
}
async function syncOdds(){const key=env("ODDS_API_KEY"),base=env("ODDS_API_BASE_URL","https://api.the-odds-api.com/v4");if(!key)return{configured:false,synced:0,error:"ODDS_API_KEY missing"};const keys=(env("ODDS_SPORT_KEYS","soccer_uefa_champs_league,soccer_uefa_europa_league,soccer_uefa_europa_conference_league,soccer_epl")).split(",").map(x=>x.trim()).filter(Boolean);const {data:matches}=await sb.from("football_matches").select("id,home_team,away_team,kickoff_at").gte("kickoff_at",new Date().toISOString()).limit(1000);const list=matches||[];let synced=0,failed=0,events=0;for(const sport of keys){let payload:any;try{payload=(await jsonFetch(base+"/sports/"+encodeURIComponent(sport)+"/odds?regions=eu&markets=h2h&oddsFormat=decimal&apiKey="+encodeURIComponent(key))).data}catch{continue}for(const ev of (Array.isArray(payload)?payload:[])){events++;const match=list.find((m:any)=>norm(m.home_team)===norm(ev.home_team)&&norm(m.away_team)===norm(ev.away_team)&&Math.abs(new Date(m.kickoff_at).getTime()-new Date(ev.commence_time).getTime())<4*3600000);if(!match)continue;for(const bm of (ev.bookmakers||[])){for(const market of (bm.markets||[])){for(const o of (market.outcomes||[])){const row={match_id:match.id,market:market.key,selection:o.name,odds:Number(o.price),bookmaker:bm.title||bm.key,captured_at:bm.last_update||new Date().toISOString()};const {data:oldOdds}=await sb.from("football_odds").select("id").eq("match_id",match.id).eq("market",row.market).eq("selection",row.selection).eq("bookmaker",row.bookmaker).limit(1).maybeSingle();const q=oldOdds?.id?await sb.from("football_odds").update(row).eq("id",oldOdds.id):await sb.from("football_odds").insert(row);if(q.error)failed++;else synced++}}}}}return{configured:true,synced,failed,events,sports:keys}} 
const footballConfigured=()=>Boolean(env("SPORTMONKS_API_TOKEN")||env("SPORT_API_KEY")||env("FOOTBALL_API_KEY"));
const oddsConfigured=()=>Boolean(env("ODDS_API_KEY"));
async function syncExternalData(force=false){const now=Date.now();const football=force||now-lastFootballSync>10*60*1000?await syncFootball():{configured:footballConfigured(),skipped:true};if(football.configured&&!football.error)lastFootballSync=now;const odds=force||now-lastOddsSync>30*60*1000?await syncOdds():{configured:oddsConfigured(),skipped:true};if(odds.configured&&!odds.error)lastOddsSync=now;const {count:matchCount}=await sb.from("football_matches").select("*",{count:"exact",head:true});const {count:oddsCount}=await sb.from("football_odds").select("*",{count:"exact",head:true});return{football,odds,database:{football_matches:matchCount||0,football_odds:oddsCount||0},synced_at:new Date().toISOString()}}
async function connectivity(){const {count:matchCount}=await sb.from("football_matches").select("*",{count:"exact",head:true});const {count:oddsCount}=await sb.from("football_odds").select("*",{count:"exact",head:true});const {count:statsCount}=await sb.from("football_team_stats").select("*",{count:"exact",head:true});return{providers:{football_api:footballConfigured(),odds_api:oddsConfigured(),groq:Boolean(env("GROQ_API_KEY")),openai:Boolean(env("OPENAI_API_KEY")),news:true},database:{football_matches:matchCount||0,football_odds:oddsCount||0,football_team_stats:statsCount||0},updated_at:new Date().toISOString()}}
async function diagnostics(){const checkedAt=new Date().toISOString();const result:any={checked_at:checkedAt,providers:{},database:{},sync:{football_last_ok:lastFootballSync?new Date(lastFootballSync).toISOString():null,odds_last_ok:lastOddsSync?new Date(lastOddsSync).toISOString():null}};
const db=await sb.from("football_matches").select("*",{count:"exact",head:true});const od=await sb.from("football_odds").select("*",{count:"exact",head:true});const st=await sb.from("football_team_stats").select("*",{count:"exact",head:true});
result.database={football_matches:db.count||0,football_odds:od.count||0,football_team_stats:st.count||0,status:db.error||od.error||st.error?"DEGRADED":"HEALTHY"};
const sportmonks=env("SPORTMONKS_API_TOKEN")||env("SPORT_API_KEY");if(sportmonks){try{const today=apiDate(new Date());await jsonFetch(env("SPORTMONKS_API_BASE_URL","https://api.sportmonks.com/v3/football")+"/fixtures/between/"+today+"/"+today+"?api_token="+encodeURIComponent(sportmonks)+"&per_page=1",{headers:{accept:"application/json"}},9000);result.providers.football_api={status:"CONNECTED",provider:"Sportmonks",detail:"Fixtures endpoint OK · auth + plan access confirmed"}}catch(e){result.providers.football_api={status:"ERROR",provider:"Sportmonks",detail:e instanceof Error?e.message:String(e)}}}else if(env("FOOTBALL_API_KEY")){try{await jsonFetch(env("FOOTBALL_API_BASE_URL","https://v3.football.api-sports.io")+"/status",{headers:{"x-apisports-key":env("FOOTBALL_API_KEY"),accept:"application/json"}},9000);result.providers.football_api={status:"CONNECTED",provider:"API-Football",detail:"Live API handshake OK"}}catch(e){result.providers.football_api={status:"ERROR",provider:"API-Football",detail:e instanceof Error?e.message:String(e)}}}else result.providers.football_api={status:"OFFLINE",provider:"—",detail:"Ingen football API-secret"};
if(env("ODDS_API_KEY")){try{await jsonFetch(env("ODDS_API_BASE_URL","https://api.the-odds-api.com/v4")+"/sports?apiKey="+encodeURIComponent(env("ODDS_API_KEY")),{},9000);result.providers.odds_api={status:"CONNECTED",provider:"The Odds API",detail:"Live API handshake OK"}}catch(e){result.providers.odds_api={status:"ERROR",provider:"The Odds API",detail:e instanceof Error?e.message:String(e)}}}else result.providers.odds_api={status:"OFFLINE",provider:"—",detail:"ODDS_API_KEY mangler"};
if(env("GROQ_API_KEY")){try{await jsonFetch("https://api.groq.com/openai/v1/models",{headers:{authorization:"Bearer "+env("GROQ_API_KEY")},},9000);result.providers.groq={status:"CONNECTED",provider:"Groq",detail:"Auth handshake OK"}}catch(e){result.providers.groq={status:"ERROR",provider:"Groq",detail:e instanceof Error?e.message:String(e)}}}else result.providers.groq={status:"OFFLINE",provider:"—",detail:"GROQ_API_KEY mangler"};
if(env("OPENAI_API_KEY")){try{await jsonFetch("https://api.openai.com/v1/models",{headers:{authorization:"Bearer "+env("OPENAI_API_KEY")}},9000);result.providers.openai={status:"CONNECTED",provider:"OpenAI",detail:"Auth handshake OK"}}catch(e){result.providers.openai={status:"ERROR",provider:"OpenAI",detail:e instanceof Error?e.message:String(e)}}}else result.providers.openai={status:"OFFLINE",provider:"—",detail:"OPENAI_API_KEY mangler"};
try{await fetchNewsJson("https://api.gdeltproject.org/api/v2/doc/doc?query=football&mode=artlist&maxrecords=1&format=json",5000);result.providers.news={status:"CONNECTED",provider:"GDELT",detail:"News endpoint reachable"}}catch(e){result.providers.news={status:"ERROR",provider:"GDELT",detail:e instanceof Error?e.message:String(e)}}
const errors=Object.values(result.providers).filter((x:any)=>x.status==="ERROR").length;result.status=errors?"DEGRADED":"HEALTHY";return result}
async function top6(){const s=await getSettings();if(s.football_api_enabled!==false||s.odds_api_enabled!==false)await syncExternalData(false);const ms=await getMatches(),st=await getStats(),{data:state}=await sb.from("football_ai_model_weights").select("*").eq("model_name","trademindmz-v3").maybeSingle();const ranked=ms.map(m=>({...m,model:preScore(m,st,state?.weights)})).sort((a,b)=>b.model.score-a.model.score).slice(0,6);const result=[];for(const m of ranked){const ns=s.news_enabled?await newsFor(m):[];const {data:od}=s.odds_api_enabled?await sb.from("football_odds").select("market,selection,odds,bookmaker,captured_at").eq("match_id",m.id).order("captured_at",{ascending:false}).limit(20):{data:[]};const ai=await deep(m,s,ns,od||[]);const {data:existing}=await sb.from("football_ai_predictions").select("id").eq("match_id",m.id).eq("status","OPEN").limit(1).maybeSingle();const pred={match_id:m.id,prediction:ai.prediction||m.model.selected,selected_outcome:ai.prediction||m.model.selected,confidence:Number(ai.confidence||0),implied_probability:Number(ai.probabilities?.home||0),odds:od?.[0]?.odds||null,value_percent:ai.value_percent,model_score:m.model.score,reasoning:{reasoning:ai.reasoning,news:ns},provider:ai.provider,model:ai.model,status:"OPEN",feature_vector:m.model.features,feature_version:"v3-top6",model_version:state?.model_version||"v3.0"};let saved:any=null;if(existing?.id){const {data:u}=await sb.from("football_ai_predictions").update(pred).eq("id",existing.id).select().single();saved=u}else{const {data:i}=await sb.from("football_ai_predictions").insert(pred).select().single();saved=i}if(saved)result.push({...m,ai,prediction:saved});}return {matches_scanned:ms.length,top6:result}}
async function evaluate(){const {data:ps}=await sb.from("football_ai_predictions").select("id,match_id,prediction,odds").eq("status","OPEN").limit(500);if(!ps?.length)return{evaluated:0};const {data:ms}=await sb.from("football_matches").select("id,status,home_score,away_score").in("id",ps.map(x=>x.match_id));let n=0;for(const p of ps){const m=ms?.find(x=>x.id===p.match_id);if(!m||VOID.has(String(m.status||"").toLowerCase())||m.home_score==null||m.away_score==null)continue;const actual=m.home_score>m.away_score?"1":m.home_score<m.away_score?"2":"X",correct=String(p.prediction)===actual,pnl=p.odds&&Number(p.odds)>1?(correct?Number(p.odds)-1:-1):null;await sb.from("football_ai_predictions").update({status:correct?"WON":"LOST",settled_result:actual,pnl,evaluated_at:new Date().toISOString()}).eq("id",p.id);await sb.from("football_ai_evaluations").upsert({prediction_id:p.id,match_id:p.match_id,actual_result:actual,predicted_result:p.prediction,correct,stake:1,pnl,evaluated_at:new Date().toISOString()},{onConflict:"prediction_id"});n++}return{evaluated:n}}
async function learning(){const {data:e}=await sb.from("football_ai_evaluations").select("correct,pnl").order("evaluated_at",{ascending:false}).limit(1000);const rows=e||[],correct=rows.filter(x=>x.correct).length,accuracy=rows.length?correct/rows.length:null,roi=rows.length?rows.reduce((a,x)=>a+Number(x.pnl||0),0)/rows.length:0;const {data:old}=await sb.from("football_ai_model_weights").select("*").eq("model_name","trademindmz-v3").maybeSingle();const weights={...(old?.weights||{home:1,draw:.1,away:-1})};const lr=Number(old?.learning_rate||.02);if(accuracy!=null){weights.home+=lr*(accuracy-.5);weights.away-=lr*(accuracy-.5)}await sb.from("football_ai_model_weights").upsert({model_name:"trademindmz-v3",model_version:"v3."+rows.length,weights,bias:old?.bias||{home:0,draw:0,away:0},learning_rate:lr,training_samples:rows.length,accuracy,roi,updated_at:new Date().toISOString()});return{samples:rows.length,accuracy,roi}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return out(200,{});try{const b=await req.json().catch(()=>({}));const a=b.action||"top6";if(a==="settings")return out(200,await getSettings());if(a==="connectivity")return out(200,await connectivity());if(a==="diagnostics")return out(200,await diagnostics());if(a==="sync")return out(200,await syncExternalData(true));if(a==="update_settings"){const current=await getSettings();const next={...current,...(b.settings||{}),updated_at:new Date().toISOString()};const {data,error}=await sb.from("football_ai_settings").upsert({...next,id:true}).select().single();if(error)throw error;return out(200,data||next);}if(a==="top6"||a==="pipeline")return out(200,await top6());if(a==="evaluate")return out(200,await evaluate());if(a==="results"){await evaluate();const {data:allPs}=await sb.from("football_ai_predictions").select("id,match_id,prediction,selected_outcome,confidence,odds,value_percent,provider,model,status,settled_result,pnl,evaluated_at,created_at").order("created_at",{ascending:false}).limit(200);const ps=allPs||[];const osloDay=(v:any)=>{if(!v)return"";try{return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Oslo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(v))}catch{return String(v).slice(0,10)}};const latestDay=osloDay(ps[0]?.created_at);const todayPs=latestDay?ps.filter((x:any)=>osloDay(x.created_at)===latestDay).slice(0,6):[];const selected=todayPs.length?todayPs:ps.slice(0,6);const ids=selected.map((x:any)=>x.match_id).filter(Boolean);let ms:any[]=[];if(ids.length){const {data}=await sb.from("football_matches").select("id,home_team,away_team,league,kickoff_at,home_score,away_score,status").in("id",ids);ms=data||[]}const matches=new Map(ms.map((m:any)=>[m.id,m]));const rows=selected.map((p:any)=>({...p,match:matches.get(p.match_id)||null}));const settled=rows.filter((x:any)=>x.status==="WON"||x.status==="LOST");const wins=settled.filter((x:any)=>x.status==="WON").length;const pnl=settled.reduce((a:any,x:any)=>a+Number(x.pnl||0),0);return out(200,{results:rows,summary:{batch_date:latestDay||null,batch_size:rows.length,evaluated:settled.length,wins,losses:settled.filter((x:any)=>x.status==="LOST").length,pending:rows.filter((x:any)=>x.status==="OPEN").length,accuracy:settled.length?Math.round(wins/settled.length*100):null,roi:settled.length?Math.round(pnl/settled.length*1000)/10:0}})}
if(a==="performance"){const {data:e}=await sb.from("football_ai_evaluations").select("correct,pnl,evaluated_at").order("evaluated_at",{ascending:false}).limit(1000);const rows=e||[];const {data:w}=await sb.from("football_ai_model_weights").select("*").eq("model_name","trademindmz-v3").maybeSingle();const calc=(xs:any[])=>{const n=xs.length,wins=xs.filter(x=>x.correct).length,pnl=xs.reduce((a,x)=>a+Number(x.pnl||0),0);return{samples:n,wins,losses:n-wins,accuracy:n?Math.round(wins/n*100):null,roi:n?Math.round(pnl/n*1000)/10:0,pnl:Math.round(pnl*100)/100}};const recent=calc(rows.slice(0,20)),previous=calc(rows.slice(20,40));const trend=recent.accuracy==null||previous.accuracy==null?"STABLE":recent.accuracy>previous.accuracy?"IMPROVING":recent.accuracy<previous.accuracy?"ADJUSTING":"STABLE";const weights=w?.weights||{home:1,draw:.1,away:-1};return out(200,{model:{name:"TMZ-AI",version:w?.model_version||"v3.0",samples:w?.training_samples||rows.length,learning_rate:w?.learning_rate||.02,updated_at:w?.updated_at||null,trend,weights},metrics:{...calc(rows),recent,previous},pipeline:["Resultater","Evaluering","Error scan","Weight update","Validation"],signals:[{name:"ACCURACY",value:recent.accuracy||0,status:trend},{name:"VALUE",value:Math.max(0,Math.min(100,50+recent.roi*4)),status:recent.roi>=0?"POSITIVE":"NEGATIVE"},{name:"DATA QUALITY",value:Math.min(100,Math.round(rows.length/10)),status:rows.length>=100?"STRONG":rows.length>=30?"BUILDING":"COLLECTING"},{name:"LEARNING",value:Math.min(100,Math.round((w?.training_samples||rows.length)/5)),status:trend}]});}if(a==="learning")return out(200,await learning());async function fetchNewsJson(url:string,ms=4500,init?:RequestInit){const ac=new AbortController();const timer=setTimeout(()=>ac.abort(),ms);try{const r=await fetch(url,{...(init||{}),signal:ac.signal});if(!r.ok)return null;return await r.json()}catch{return null}finally{clearTimeout(timer)}}
async function newsFeed(s:any){if(s.news_enabled===false)return{news:[],source:"News Engine disabled",summary:{count:0,avg_relevance:0,high_impact:0,ai_active:false}};const url="https://api.gdeltproject.org/api/v2/doc/doc?query="+encodeURIComponent("football Europe soccer injuries lineup suspension form")+"&mode=artlist&maxrecords=12&format=json&sort=datedesc";const j=await fetchNewsJson(url,4500);const articles=(j?.articles||[]).filter((a:any)=>a?.title).map((a:any)=>({title:a.title,source:a.domain||a.source,url:a.url,published_at:a.seendate?new Date(a.seendate).toISOString():null}));if(!articles.length)return{news:[],source:"GDELT",summary:{count:0,avg_relevance:0,high_impact:0,ai_active:false}};let enriched=articles.map((x:any)=>({...x,category:/injur|hurt|fitness|sidelined|out/i.test(x.title)?"INJURY":/lineup|starting|xi|formation/i.test(x.title)?"LINEUP":/trend|form|win|loss|unbeaten/i.test(x.title)?"TREND":"TEAM",relevance:55,impact:"MEDIUM",summary:"AI analyserer relevansen for kommende europeiske kamper."}));let providerUrl="",key="",model="";if(s.groq_enabled&&Deno.env.get("GROQ_API_KEY")){providerUrl="https://api.groq.com/openai/v1/chat/completions";key=Deno.env.get("GROQ_API_KEY")!;model=Deno.env.get("GROQ_MODEL")||"llama-3.3-70b-versatile"}else if(s.openai_enabled&&Deno.env.get("OPENAI_API_KEY")){providerUrl="https://api.openai.com/v1/chat/completions";key=Deno.env.get("OPENAI_API_KEY")!;model=Deno.env.get("OPENAI_MODEL")||"gpt-4o-mini"}if(providerUrl){try{const prompt="Classify these football news articles. Return JSON object with key news. Each item: category (TEAM, INJURY, LINEUP, TREND), relevance (0-100), impact (LOW, MEDIUM, HIGH), summary (max 18 words). Only use supplied titles. Articles: "+JSON.stringify(enriched);const body=JSON.stringify({model,messages:[{role:"system",content:"You are TradeMindMZ News AI. Only use facts in supplied article titles. Return valid JSON."},{role:"user",content:prompt}],temperature:.1,response_format:{type:"json_object"}});const j=await fetchNewsJson(providerUrl,5000,{method:"POST",headers:{"authorization":"Bearer "+key,"content-type":"application/json"},body});if(j){try{const parsed=JSON.parse(j.choices?.[0]?.message?.content||"{}");const aiRows=Array.isArray(parsed)?parsed:(parsed.news||parsed.articles||[]);enriched=enriched.map((x:any,i:number)=>({...x,...(aiRows[i]||{})}))}catch{}}}catch{}}const avg=Math.round(enriched.reduce((a:any,x:any)=>a+Number(x.relevance||0),0)/Math.max(1,enriched.length));return{news:enriched,source:"GDELT",summary:{count:enriched.length,avg_relevance:avg,high_impact:enriched.filter(x=>String(x.impact).toUpperCase()==="HIGH").length,ai_active:Boolean(providerUrl)}}}
if(a==="news")return out(200,{news:await newsFeed(await getSettings())});return out(400,{error:"unknown_action"});}catch(e){return out(500,{error:e instanceof Error?e.message:String(e)});}});