import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,Trophy,Globe2,LineChart,Newspaper,BarChart3,FlaskConical,Clock3,Target,Settings,ChevronRight,CheckCircle2,Brain,Database,Activity,ShieldAlert,Search,CalendarDays,Bell,Menu,X,TrendingUp,Zap} from 'lucide-react';
import './styles.css';
import {checkSupabaseConnection} from './lib/supabase.js';
import {getFootballDashboard,syncFootballData,getFootballHistory} from './lib/footballApi.js';

const picks=[
 {league:'Premier League',time:'16:00',home:'Liverpool',away:'Everton',homeShort:'LIV',awayShort:'EVE',tip:'Liverpool vinner',confidence:78,odds:'1.62',signal:'STARKT SIGNAL',value:'++',reasons:['Sterk hjemmeform (8-1-1)','Høyere xG (2.08 vs 1.11)','Everton flere skadefravær','Ekspert 7/10 mot Liverpool','Historisk sterk hjemmebane']},
 {league:'La Liga',time:'21:00',home:'Barcelona',away:'Sevilla',homeShort:'BAR',awayShort:'SEV',tip:'Over 2.5 mål',confidence:71,odds:'1.70',signal:'MODERAT SIGNAL',value:'++',reasons:['Begge lag scorer i 73% av kampene','Høyt tempo og offensiv spillestil','Barcelona høy xG (2.14)','Sevilla svak borteform','Eksperter 6/10 over 2.5 mål']}
];
const games=[['16:00','PL','Liverpool – Everton','Liverpool vinner','78%','1.62','++'],['18:30','Bundesliga','Bayern – Dortmund','Over 2.5 mål','66%','1.58','+'],['19:00','Serie A','Inter – Roma','Begge lag scorer','64%','1.72','+'],['21:00','La Liga','Barcelona – Sevilla','Over 2.5 mål','71%','1.70','++'],['21:00','Ligue 1','PSG – Marseille','PSG vinner','63%','1.65','+']];
const news=[['LIV','Salah tilgjengelig mot Everton','Liverpool-stjernen er tilbake i dagens kamptropp.','2 timer siden'],['BAR','Pedri usikker til kveldens kamp','Barcelona-midtbane-spilleren vurderes frem til kampstart.','3 timer siden'],['LA','Eksperter forventer mål fest','Flere eksperter mener Barcelona – Sevilla kan bli en åpen kamp.','4 timer siden']];
function Sidebar({active,setActive,mobile,setMobile}){const items=[['Hjem',Home],['Dagens tips',Trophy],['Alle kamper',Globe2],['AI analyse',LineChart],['Ekspertanalyse',Newspaper],['Statistikk',BarChart3],['Model Lab',FlaskConical],['Historikk',Clock3],['Value Finder',Target],['Innstillinger',Settings]];return <aside className={'sidebar '+(mobile?'open':'')}><div className="sideTop"><div className="brandMini"><span className="mzMark">M</span><div>TRADE<span>MIND</span><b>MZ</b></div></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><nav>{items.map(([label,Icon])=><button key={label} className={active===label?'active':''} onClick={()=>{setActive(label);setMobile(false)}}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="sideNews"><div className="avatar">◉</div><div><small>SISTE NYTT</small><strong>Live AI-data</strong></div></div></aside>}
function Header({setMobile,onSync,syncing}){const [db,setDb]=useState({ok:false,status:'CHECKING'});useEffect(()=>{checkSupabaseConnection().then(setDb)},[]);const today=new Intl.DateTimeFormat('nb-NO',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());return <header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div className="heroBrand"><div className="brandLogoMark">M</div><div><h1>TRADEMIND<em>MZ</em></h1><p>AI POWERED FOOTBALL INSIGHTS</p></div></div><div className="tagline">DATA + AI + ODDS <span>= SMARTER DECISIONS</span></div><div className="headRight"><button className="syncBtn" onClick={onSync} disabled={syncing}>{syncing?'SYNKRONISERER…':'↻ OPPDATER LIVE'}</button><div className={'dbStatus '+(db.ok?'online':'offline')}><span/>SUPABASE {db.ok?'ONLINE':'OFFLINE'}</div><div className="date"><CalendarDays size={17}/>{today}</div><Bell className="bell" size={20}/><div className="user">MZ⌄</div></div></header>}
function StatBar({matches,predictions,engine}){const evaluation=engine?.evaluation||{};const model=engine?.model||{};const items=[['⚽','KOMMENDE KAMPER',matches??'–'],['▥','ANALYSERTE KAMPER',matches??'–'],['★','AI KANDIDATER',predictions??'–'],['🏆','ÅPNE PREDIKSJONER',predictions??'–'],['◉','TREFFSIKKERHET',evaluation.accuracy!=null?evaluation.accuracy.toFixed(1)+'%':'–']];return <div className="statbar">{items.map(x=><div className="stat" key={x[1]}><i>{x[0]}</i><div><small>{x[1]}</small><strong>{x[2]}</strong></div></div>)}</div>}
function PickCard({p,index}){return <div className={'pick '+(index===0?'green':'gold')}><div className="pickHead"><b>🏆 PICK #{index+1}</b><span>{p.signal}</span></div><div className="match"><div><div className="crest">{p.homeShort}</div><strong>{p.home}</strong></div><div className="vs"><small>{p.league} · I dag · {p.time}</small>VS</div><div><div className="crest away">{p.awayShort}</div><strong>{p.away}</strong></div></div><div className="tipRow"><div className="tipBox"><small>TIPS</small><strong>{p.tip}</strong></div><div className="confidence"><small>AI CONFIDENCE</small><div className="ring" style={{'--v':p.confidence+'%'}}>{p.confidence}%</div></div><div className="odds"><small>ODDS</small><strong>{p.odds}</strong></div></div><ul>{p.reasons.map(r=><li key={r}><CheckCircle2 size={16}/>{r}</li>)}</ul><button className="analyse">SE FULL ANALYSE <ChevronRight size={16}/></button></div>}
function Engine({engine}){const model=engine?.model||{};return <aside className="rightcol"><section className="panel"><div className="panelTitle"><Brain/>FOOTBALL AI ENGINE <ChevronRight/></div><div className="aiPair"><div><b>◈</b><span>GROQ<small>REASONING</small></span></div><strong>+</strong><div><b className="openai">◉</b><span>OpenAI<small>DYP ANALYSE</small></span></div></div><div className="engineMetrics"><div><small>MODELL</small><b>{model.model_version||'football-multinomial-v1'}</b></div><div><small>LÆRINGSDATA</small><b>{model.training_samples??0}</b></div><div><small>TREFFSIKKERHET</small><b>{model.accuracy!=null?(model.accuracy*100).toFixed(1)+'%':'–'}</b></div><div><small>ROI / ENHET</small><b>{model.roi!=null?(model.roi*100).toFixed(2)+'%':'–'}</b></div></div><div className="pipelineMini">{['FORM','xG/PROXY','RESULTATER','ODDS','PROBABILITY','VALUE','EVALUERING','LÆRING'].map((x,i)=><span key={x} className={i<7?'done':''}>{x}</span>)}</div></section><section className="panel"><div className="panelTitle"><FlaskConical/>MODEL LAB <small>(LIVE)</small><ChevronRight/></div><div className="lab"><span>Treningsdata <b>{model.training_samples??0}</b></span><span>Treffsikkerhet <b className="greenTxt">{model.accuracy!=null?(model.accuracy*100).toFixed(1)+'%':'–'}</b></span><span>ROI <b className="greenTxt">{model.roi!=null?(model.roi*100).toFixed(2)+'%':'–'}</b></span><span>Brier <b>{model.brier_score!=null?Number(model.brier_score).toFixed(3):'–'}</b></span></div></section><section className="panel week"><div className="panelTitle"><Database/>DATAKVALITET</div><div className="dataStatusRow"><span>Evalueringer</span><b>{engine?.evaluation?.samples??0}</b></div><div className="dataStatusRow"><span>Treffsikkerhet</span><b>{engine?.evaluation?.accuracy!=null?Number(engine.evaluation.accuracy).toFixed(1)+'%':'–'}</b></div><div className="dataStatusRow"><span>ROI / enhet</span><b>{engine?.evaluation?.roi_percent_per_unit!=null?Number(engine.evaluation.roi_percent_per_unit).toFixed(2)+'%':'–'}</b></div></section></aside>}
function Bottom({predictions,engine}){const value=(predictions||[]).filter(p=>p.value_percent!=null&&Number(p.value_percent)>0).sort((a,b)=>Number(b.value_percent)-Number(a.value_percent)).slice(0,6);const model=engine?.model||{};return <div className="bottom"><section className="panel news"><div className="panelTitle"><Target/> VALUE FINDER <small>(LIVE)</small></div>{value.length?value.map(p=><div className="newsrow" key={p.id}><div className="newsLogo">+</div><div><b>{p.prediction}</b><p>AI {Number(p.confidence).toFixed(1)}% · Odds {p.odds?Number(p.odds).toFixed(2):'–'}</p></div><strong className="greenTxt">+{Number(p.value_percent).toFixed(1)}%</strong></div>):<div className="emptyState">Ingen positiv value registrert akkurat nå.</div>}</section><section className="panel experts"><div className="panelTitle"><Database/> DATASTATUS</div><div className="dataStatusRow"><span>Kommende kamper</span><b>{predictions?.length||0}</b></div><div className="dataStatusRow"><span>Tips med odds</span><b>{(predictions||[]).filter(p=>p.odds&&Number(p.odds)>1).length}</b></div><div className="dataStatusRow"><span>Positive value</span><b className="greenTxt">{value.length}</b></div><div className="dataStatusRow"><span>Modell</span><b>{model.model_version||'–'}</b></div><div className="dataStatusRow"><span>Treningsdata</span><b>{model.training_samples??0}</b></div></section><section className="panel score"><div className="panelTitle"><Zap/> AI-MÅLINGER <small>(LIVE)</small></div><div className="scoreline"><span>Treffsikkerhet</span><i><em style={{width:(model.accuracy!=null?model.accuracy*100:0)+'%'}}/></i><b>{model.accuracy!=null?(model.accuracy*100).toFixed(1)+'%':'–'}</b></div><div className="scoreline"><span>ROI</span><i><em style={{width:Math.max(0,Math.min(100,(model.roi||0)*100))+'%'}}/></i><b>{model.roi!=null?(model.roi*100).toFixed(2)+'%':'–'}</b></div><div className="scoreline"><span>Brier</span><i><em style={{width:model.brier_score!=null?Math.max(0,Math.min(100,(1-model.brier_score)*100)):0+'%'}}/></i><b>{model.brier_score!=null?Number(model.brier_score).toFixed(3):'–'}</b></div><div className="total">DATA + MODEL + RESULTAT <b>LIVE</b></div></section></div>}
function PageTitle({title,sub}){return <div className="sectionTitle"><span/>{title}<small>{sub||''}</small></div>}

function MatchesTable({matches,predictions}){const by=new Map((predictions||[]).map(p=>[p.match_id,p]));return <div className="table panel"><div className="tr th"><span>TID</span><span>LIGA</span><span>KAMP</span><span>TIPS</span><span>AI %</span><span>ODDS</span><span>VERDI</span><span>STATUS</span></div>{(matches||[]).map(m=>{const p=by.get(m.id);const kickoff=new Date(m.kickoff_at);const status=String(m.status||'').toLowerCase();const finished=status.includes('finish')||m.home_score!=null;const live=!finished&&kickoff.getTime()<=Date.now();return <div className="tr" key={m.id}><span>{kickoff.toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'})}</span><span>{m.league||'–'}</span><span>{m.home_team} – {m.away_team}</span><span>{p?.prediction||'–'}</span><span className="greenTxt">{p?Math.round(Number(p.confidence||0))+'%':'–'}</span><span>{p?.odds?Number(p.odds).toFixed(2):'–'}</span><span className={p&&Number(p.value_percent)>0?'greenTxt':''}>{p?.value_percent!=null?Number(p.value_percent).toFixed(1)+'%':'–'}</span><span className="status">{finished?'● '+(m.home_score??0)+'–'+(m.away_score??0):live?'● LIVE':'● Ikke startet'}</span></div>})}</div>}

function ValuePage({predictions}){const values=(predictions||[]).filter(p=>p.value_percent!=null&&Number(p.value_percent)>0&&Number(p.odds)>1).sort((a,b)=>Number(b.value_percent)-Number(a.value_percent));return <><PageTitle title="VALUE FINDER" sub="LIVE · POSITIVE VALUE"/><div className="pageGrid"><section className="panel"><div className="panelTitle"><Target/> POSITIVE VALUE <small>{values.length} FUNNET</small></div>{values.length?values.map(p=><div className="valueCard" key={p.id}><div><b>{p.prediction}</b><small>AI {Number(p.confidence).toFixed(1)}% · Implied {p.implied_probability?Number(p.implied_probability).toFixed(1)+'%':'–'} · Odds {Number(p.odds).toFixed(2)}</small></div><strong className="greenTxt">+{Number(p.value_percent).toFixed(1)}%</strong></div>):<div className="emptyState">Ingen positiv value registrert akkurat nå.</div>}</section><section className="panel"><div className="panelTitle"><Brain/> HVORDAN VALUE BEREGNES</div><p className="pageText">Value viser modellens forventede avkastning mot tilgjengelig odds. Ingen odds betyr ingen Value Finder-score.</p><div className="formula">Value % = (modell-sannsynlighet × odds − 1) × 100</div></section></div></>}

function HistoryPage({history,onReload}){const s=history?.summary||{};return <><PageTitle title="HISTORIKK" sub="SISTE 30 DAGER"/><div className="metricGrid">{[['TIPS',s.total??0],['AVGJORTE',s.settled??0],['TREFFSIKKERHET',s.hit_rate!=null?Number(s.hit_rate).toFixed(1)+'%':'–'],['P&L',s.pnl!=null?Number(s.pnl).toFixed(2):'–']].map(([a,b])=><div className="metricCard" key={a}><small>{a}</small><strong>{b}</strong></div>)}</div><section className="panel"><div className="panelTitle"><Clock3/> RESULTATHISTORIKK <button className="miniBtn" onClick={onReload}>↻ OPPDATER</button></div><div className="historyList">{(history?.predictions||[]).slice(0,100).map(p=><div className="historyRow" key={p.id}><div><b>{p.match?.home_team||'–'} – {p.match?.away_team||'–'}</b><small>{p.match?.league||'–'} · {p.prediction} · Odds {p.odds?Number(p.odds).toFixed(2):'–'}</small></div><span className={'badge '+String(p.status||'OPEN').toLowerCase()}>{p.status||'OPEN'}</span><strong className={Number(p.pnl)>0?'greenTxt':''}>{p.pnl!=null?Number(p.pnl).toFixed(2):'–'}</strong></div>)}</div></section></>}

function StatsPage({history,engine}){const s=history?.summary||{},m=history?.model||engine?.model||{};return <><PageTitle title="STATISTIKK" sub="DATA + RESULTATER"/><div className="metricGrid">{[['TREFFSIKKERHET',s.hit_rate!=null?Number(s.hit_rate).toFixed(1)+'%':'–'],['ROI',m.roi!=null?(Number(m.roi)*100).toFixed(2)+'%':'–'],['BRIER',m.brier_score!=null?Number(m.brier_score).toFixed(3):'–'],['LOG LOSS',m.log_loss!=null?Number(m.log_loss).toFixed(3):'–']].map(([a,b])=><div className="metricCard" key={a}><small>{a}</small><strong>{b}</strong></div>)}</div><div className="pageGrid"><section className="panel"><div className="panelTitle"><BarChart3/> LIGAOVERSIKT</div>{(history?.leagues||[]).map(l=><div className="dataStatusRow" key={l.league}><span>{l.league}</span><b>{l.wins}W · {l.losses}L · {Number(l.pnl).toFixed(2)}</b></div>)}{!history?.leagues?.length&&<div className="emptyState">Ingen avgjorte tips i perioden.</div>}</section><section className="panel"><div className="panelTitle"><Activity/> MODELLMÅLINGER</div><div className="dataStatusRow"><span>Treningsdata</span><b>{m.training_samples??0}</b></div><div className="dataStatusRow"><span>Modellversjon</span><b>{m.model_version||'–'}</b></div><div className="dataStatusRow"><span>Oppdatert</span><b>{m.updated_at?new Date(m.updated_at).toLocaleString('nb-NO'):'–'}</b></div></section></div></>}

function ModelPage({engine,history,onTrain}){const m=history?.model||engine?.model||{};return <><PageTitle title="MODEL LAB" sub="LIVE LÆRING"/><div className="metricGrid">{[['MODELL',m.model_version||'–'],['TRENINGSDATA',m.training_samples??0],['TREFFSIKKERHET',m.accuracy!=null?(Number(m.accuracy)*100).toFixed(1)+'%':'–'],['ROI',m.roi!=null?(Number(m.roi)*100).toFixed(2)+'%':'–']].map(([a,b])=><div className="metricCard" key={a}><small>{a}</small><strong>{b}</strong></div>)}</div><section className="panel"><div className="panelTitle"><FlaskConical/> LÆRINGSMODELL <button className="miniBtn" onClick={onTrain}>↻ TREN MODELL</button></div><p className="pageText">Modellen trener på evaluerte historiske prediksjoner. Nye resultater brukes først etter at kampene er avgjort.</p><div className="pipelineLarge">{['FORM','xG/PROXY','RESULTATER','ODDS','PROBABILITY','VALUE','EVALUERING','LÆRING','RETRAIN'].map((x,i)=><span key={x} className={i<8?'done':''}>{i+1}. {x}</span>)}</div></section></>}

function AiAnalysisPage({predictions}){const rows=(predictions||[]).slice(0,20);return <><PageTitle title="AI ANALYSE" sub="MODELLENS AKTUELLE VURDERINGER"/><section className="panel"><div className="panelTitle"><Brain/> PREDIKSJONSANALYSE</div>{rows.length?rows.map(p=><div className="analysisRow" key={p.id}><div><b>{p.prediction}</b><small>Confidence {Number(p.confidence||0).toFixed(1)}% · Model {p.model_version||p.model||'–'}</small></div><span>Odds {p.odds?Number(p.odds).toFixed(2):'–'}</span><strong className={Number(p.value_percent)>0?'greenTxt':''}>{p.value_percent!=null?Number(p.value_percent).toFixed(1)+'% value':'–'}</strong></div>):<div className="emptyState">Ingen live-prediksjoner tilgjengelig.</div>}</section></>}

function ExpertPage(){return <><PageTitle title="EKSPERTANALYSE" sub="EKSTERNE EKSPERTDATA"/><section className="panel"><div className="panelTitle"><Newspaper/> EKSPERTDATA</div><div className="emptyState">Ingen verifisert ekspertkilde er koblet til akkurat nå. Appen viser derfor ikke oppdiktede ekspertuttalelser eller nyheter.</div></section></>}

function SettingsPage(){return <><PageTitle title="INNSTILLINGER" sub="TRADEMINDMZ"/><div className="pageGrid"><section className="panel"><div className="panelTitle"><Settings/> SYSTEM</div><div className="dataStatusRow"><span>Datakilde</span><b>Football Soccer API</b></div><div className="dataStatusRow"><span>Backend</span><b>Supabase Edge Function</b></div><div className="dataStatusRow"><span>Modell</span><b>Multinomial AI</b></div><div className="dataStatusRow"><span>Persistens</span><b>Supabase</b></div></section><section className="panel"><div className="panelTitle"><ShieldAlert/> DATAPRINSIPPER</div><p className="pageText">Ingen demo-tips brukes når live-data mangler. Skade- og xG-data vises bare når leverandøren faktisk leverer dem.</p></section></div></>}

function MobileNav({active,setActive}){const items=[["Hjem",Home],["Alle kamper",Globe2],["AI analyse",Brain],["Statistikk",BarChart3],["Value Finder",Target]];return <nav className="mobileNav">{items.map(([label,Icon])=><button key={label} className={active===label?"active":""} onClick={()=>setActive(label)}><Icon size={19}/><span>{label==="Alle kamper"?"Kamper":label==="Value Finder"?"Value":label.replace(" analyse","")}</span></button>)}</nav>}

function Main(){
  const [active,setActive]=useState('Hjem'),[mobile,setMobile]=useState(false),[liveMatches,setLiveMatches]=useState([]),[livePredictions,setLivePredictions]=useState([]),[engine,setEngine]=useState({}),[syncing,setSyncing]=useState(false),[liveError,setLiveError]=useState(''),[history,setHistory]=useState(null),[historyLoading,setHistoryLoading]=useState(false);

  const loadLive=async()=>{try{const data=await getFootballDashboard();if(data?.ok){setLiveMatches(data.matches||[]);setLivePredictions(data.predictions||[]);setEngine(data.engine||{});setLiveError('')}}catch(e){setLiveError(e?.message||'Live-data ikke tilgjengelig')}};
  const loadHistory=async()=>{setHistoryLoading(true);try{const d=await getFootballHistory();if(d?.ok)setHistory(d)}catch(e){setLiveError(e?.message||'Historikk ikke tilgjengelig')}finally{setHistoryLoading(false)}};
  useEffect(()=>{loadLive()},[]);
  useEffect(()=>{if(['Historikk','Statistikk','Model Lab'].includes(active)&&!history&&!historyLoading)loadHistory()},[active]);

  const handleSync=async()=>{setSyncing(true);setLiveError('');try{await syncFootballData();await loadLive();if(history)await loadHistory()}catch(e){setLiveError(e?.message||'Kunne ikke synkronisere live-data')}finally{setSyncing(false)}};
  const handleTrain=async()=>{setHistoryLoading(true);try{const r=await fetch('https://imnnpilqjzfhvijhipzu.supabase.co/functions/v1/football-ai?action=train');if(!r.ok)throw new Error('Modelltrening feilet');await loadLive();await loadHistory()}catch(e){setLiveError(e?.message||'Modelltrening feilet')}finally{setHistoryLoading(false)}};

  const predictionByMatch=new Map(livePredictions.map(p=>[p.match_id,p]));
  const realPicks=liveMatches.map(m=>({match:m,prediction:predictionByMatch.get(m.id)})).filter(x=>x.prediction).slice(0,2);
  const displayPicks=realPicks.map(x=>({league:x.match.league,time:new Date(x.match.kickoff_at).toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'}),home:x.match.home_team,away:x.match.away_team,homeShort:x.match.home_team.slice(0,3).toUpperCase(),awayShort:x.match.away_team.slice(0,3).toUpperCase(),tip:x.prediction.prediction,confidence:Number(x.prediction.confidence||0),odds:x.prediction.odds?Number(x.prediction.odds).toFixed(2):'–',signal:Number(x.prediction.confidence||0)>=70?'STARKT SIGNAL':'MODERAT SIGNAL',value:Number(x.prediction.value_percent||0)>=0?'++':'+',reasons:['Modell: '+(x.prediction.model||'Football AI'),'Sannsynlighet: '+Number(x.prediction.confidence||0).toFixed(1)+'%', 'Value: '+(x.prediction.value_percent!=null?Number(x.prediction.value_percent).toFixed(1)+'%':'ikke tilgjengelig'),x.prediction.reasoning?.llm?.summary||('Datakilde: '+(x.prediction.provider||'live'))]}));
  const page=active==='Hjem'?<><div className="homeHeroTitle"><div><small>TRADEMINDMZ · LIVE INTELLIGENCE</small><h2>Kommende <em>AI-tips</em></h2><p>Modellbaserte vurderinger, odds og value samlet på ett sted.</p></div><div className="heroLive"><i/> LIVE DATA</div></div><div className="grid"><div className="center"><div className="picks">{displayPicks.map((p,i)=><PickCard key={p.home+p.away} p={p} index={i}/>)}</div><div className="filters"><button className="selected">Kommende kamper (live)</button>{['Premier League','La Liga','Serie A','Bundesliga','Champions League'].map(x=><button key={x}>{x}</button>)}</div><MatchesTable matches={liveMatches.slice(0,20)} predictions={livePredictions}/></div><Engine engine={engine}/></div><Bottom predictions={livePredictions} engine={engine}/></>
  :active==='Dagens tips'?<><PageTitle title="DAGENS TIPS" sub="KOMMENDE 2 DAGER"/><div className="picks pagePicks">{displayPicks.map((p,i)=><PickCard key={p.home+p.away} p={p} index={i}/>)}</div></>
  :active==='Alle kamper'?<><PageTitle title="ALLE KAMPER" sub={liveMatches.length+' KOMMENDE KAMPER'}/><MatchesTable matches={liveMatches} predictions={livePredictions}/></>
  :active==='Value Finder'?<ValuePage predictions={livePredictions}/>
  :active==='Historikk'?<HistoryPage history={history} onReload={loadHistory}/>
  :active==='Statistikk'?<StatsPage history={history} engine={engine}/>
  :active==='Model Lab'?<ModelPage history={history} engine={engine} onTrain={handleTrain}/>
  :active==='AI analyse'?<AiAnalysisPage predictions={livePredictions}/>
  :active==='Ekspertanalyse'?<ExpertPage/>
  :<SettingsPage/>;

  return <div className="app"><Sidebar active={active} setActive={setActive} mobile={mobile} setMobile={setMobile}/><main><Header setMobile={setMobile} onSync={handleSync} syncing={syncing}/><StatBar matches={liveMatches.length} predictions={livePredictions.length} engine={engine}/>{liveError&&<div className="liveNotice">LIVE-DATA: {liveError}</div>}{page}<MobileNav active={active} setActive={setActive}/></main></div>
}


createRoot(document.getElementById('root')).render(<Main />);
