-- TradeMindMZ V2
-- Minimal database health table.
-- This table is intentionally tiny and contains no user secrets.

create table if not exists public.trademindmz_health (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.trademindmz_health enable row level security;

-- The server uses the service-role key and therefore bypasses RLS.
-- No public insert/update/delete policies are created intentionally.
