-- TradeMindMZ V2
-- Persistent market/AI snapshots + server-side 7 minute scheduler.
-- The Android app is a viewer/client; the backend remains the analysis engine.

create extension if not exists "pgcrypto";
create extension if not exists pg_cron;
create extension if not exists pg_net;

create table if not exists public.market_ai_snapshots (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'SUCCESS'
    check (status in ('SUCCESS', 'ERROR')),
  market_type text not null default 'PERP',
  contract_type text not null default 'USDT-M PERPETUAL',
  interval text not null default '15M',
  leverage numeric not null default 2,
  scanned integer not null default 0,
  candidates jsonb not null default '[]'::jsonb,
  ai_decision jsonb,
  final_decision text not null default 'NO_TRADE',
  provider text,
  next_analysis_at timestamptz,
  payload jsonb,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists idx_market_ai_snapshots_latest
  on public.market_ai_snapshots(market_type, interval, leverage, created_at desc);

alter table public.market_ai_snapshots enable row level security;

revoke all on public.market_ai_snapshots from anon, authenticated, public;

create table if not exists public.trademind_scheduler_secrets (
  id boolean primary key default true check (id = true),
  secret text not null default encode(gen_random_bytes(32), 'hex'),
  created_at timestamptz not null default now()
);

insert into public.trademind_scheduler_secrets (id)
values (true)
on conflict (id) do nothing;

alter table public.trademind_scheduler_secrets enable row level security;
revoke all on public.trademind_scheduler_secrets from anon, authenticated, public;

create or replace function public.trademind_run_ai_scheduler()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  scheduler_secret text;
  request_id bigint;
begin
  select secret
    into scheduler_secret
    from public.trademind_scheduler_secrets
   where id = true;

  if scheduler_secret is null then
    raise exception 'TradeMindMZ scheduler secret is not configured';
  end if;

  select net.http_post(
    url := 'https://imnnpilqjzfhvijhipzu.supabase.co/functions/v1/trademind-api/api/ai/scheduled-scan',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-trademind-scheduler', scheduler_secret
    ),
    body := jsonb_build_object(
      'source', 'supabase-cron',
      'scheduledAt', now()
    ),
    timeout_milliseconds := 10000
  )
  into request_id;

  return request_id;
end;
$$;

revoke execute on function public.trademind_run_ai_scheduler() from public, anon, authenticated;

-- Recreate the job idempotently when the migration is replayed locally.
do $$
declare
  existing_job_id bigint;
begin
  select jobid
    into existing_job_id
    from cron.job
   where jobname = 'trademind-ai-every-7-minutes';

  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;

  perform cron.schedule(
    'trademind-ai-every-7-minutes',
    '*/7 * * * *',
    $job$select public.trademind_run_ai_scheduler();$job$
  );
end;
$$;

-- Keep enough history for diagnostics/learning without growing indefinitely.
do $$
declare
  existing_job_id bigint;
begin
  select jobid
    into existing_job_id
    from cron.job
   where jobname = 'trademind-ai-snapshot-cleanup';

  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;

  perform cron.schedule(
    'trademind-ai-snapshot-cleanup',
    '17 3 * * *',
    $job$delete from public.market_ai_snapshots where created_at < now() - interval '14 days';$job$
  );
end;
$$;

notify pgrst, 'reload schema';


create table if not exists public.trademind_scheduler_runs (
  id bigint generated by default as identity primary key,
  status text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  perp_snapshot_at timestamptz,
  spot_snapshot_at timestamptz,
  position_monitoring_count integer default 0,
  spot_monitoring_count integer default 0,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists idx_trademind_scheduler_runs_created
  on public.trademind_scheduler_runs(created_at desc);

alter table public.trademind_scheduler_runs enable row level security;
revoke all on public.trademind_scheduler_runs from anon, authenticated, public;
grant select, insert, update on table public.trademind_scheduler_runs to service_role;

notify pgrst, 'reload schema';


-- Spot monitoring / performance extensions.
create table if not exists public.trade_journal (
  position_key text primary key,
  symbol text not null,
  side text not null check (side in ('LONG','SHORT')),
  entry_price numeric(30,12),
  quantity numeric(30,12),
  stop_loss numeric(30,12),
  take_profit numeric(30,12),
  ai_confidence_at_entry numeric(6,3),
  ai_hold_time_min_minutes integer,
  ai_hold_time_max_minutes integer,
  ai_hold_time_reason text,
  opened_at timestamptz not null default now(),
  status text not null default 'OPEN' check (status in ('OPEN','CLOSED')),
  last_price numeric(30,12),
  last_pnl numeric(30,12),
  last_pnl_percent numeric(12,6),
  exit_price numeric(30,12),
  realized_pnl numeric(30,12),
  closed_at timestamptz,
  close_reason text,
  source text not null default 'PIONEX_READ_ONLY',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.trade_journal
  add column if not exists market_type text not null default 'PERP',
  add column if not exists fee_rate numeric(12,8),
  add column if not exists estimated_slippage_rate numeric(12,8),
  add column if not exists gross_pnl numeric(30,12),
  add column if not exists net_pnl numeric(30,12),
  add column if not exists current_value numeric(30,12),
  add column if not exists cost_basis numeric(30,12),
  add column if not exists entry_price_source text,
  add column if not exists ai_exit_recommendation text,
  add column if not exists ai_exit_confidence numeric(6,3),
  add column if not exists ai_exit_reason text;

create index if not exists idx_trade_journal_market_status
  on public.trade_journal(market_type, status, updated_at desc);

alter table public.trade_journal enable row level security;
revoke all on public.trade_journal from anon, authenticated, public;
grant select, insert, update, delete on table public.trade_journal to service_role;

notify pgrst, 'reload schema';
